### ISSUE TITLE
Add packet order validation

### ISSUE THREAD

**Issue by Octogonapus** [CommonWealthRobotics/bowler-kernel#12]
UDP can deliver packets out-of-order, repeatedly, etc. so we should handle this.

For writes, the PC increments a counter number each packet. If the device receives a packet with a counter which is not greater than the previous packet's counter, the device replies with a status code to indicate an out-of-order packet. This behavior is optional.

For reads, the device increments a counter number each packet. If the PC receives a packet with a counter which is not greater than the previous packet's counter, the latest read payload is not overwritten. This behavior is optional.

**Comment by madhephaestus** [comment]
I don't know this is useful. There is a single sending thread meaning only one packet is sent, then waited for and a single packet returned. In a timeout fail, there might be up to 2 packets, one of which is explicitly invalid. with one and only one pacente being sent, how would end up with one valid packet being behind another valid packet?

**Comment by Octogonapus** [comment]
It's useless if we 100% trust the layers below us. I think doing that is a bad idea. An incorrect program below us can send packets out of order (like a bad network driver).

**Comment by Octogonapus** [comment]
It's now clear to me that SimplePacketComs blocks packet handling when sending a packet, so no reordering can happen unless something under us seriously blows up.
